### ISSUE TITLE
Route53HostedZone parameter is confusing because most people don't put a dot at the end

### ISSUE THREAD

**Issue by irvingpop** [chef-customers/aws_native_chef_server#42]
Suggestions:
-  Change the requirement to not need a dot (auto-append this in places in the template)
-  Put a regex validator on the parameter so that it auto-rejects ones that aren't right

**Comment by irvingpop** [comment]
this is fixed by PR #50

**Comment by jerryaldrichiii** [comment]
## Summary

For anyone else coming here, using the pre-v5 config and adding the dot at the end of your Rout53HostedZone makes it so that Chef Server will not provide the authorize button when logging in via oc-id from Supermarket.

##  "Error" message for search reasons:

```
You have not granted any applications access to your Chef account
```

## Workaround

Remove the dot from the `redirect_uri` on the Chef Server Bootstrap Frontend and Supermarket and do a reconfigure on both. This did not regenerate `app_id` or `secret` for us, so you may not have to do more than just the 2 reconfigures.

Huge thanks to @teknofire for troubleshooting and finding this, no errors/warnings in the logs on any server hinted at it.

**Comment by jerryaldrichiii** [comment]
## Summary

For anyone else coming here, using the pre-v5 config and adding the dot at the end of your Route53HostedZone makes it so that Chef Server will not provide the authorize button when logging in via oc-id from Supermarket.

##  "Error" message for search reasons:

```
You have not granted any applications access to your Chef account
```

## Workaround

Remove the dot from the `redirect_uri` on the Chef Server Bootstrap Frontend and Supermarket and do a reconfigure on both. This did not regenerate `app_id` or `secret` for us, so you may not have to do more than just the 2 reconfigures.

Huge thanks to @teknofire for troubleshooting and finding this, no errors/warnings in the logs on any server hinted at it.
